### ISSUE TITLE
Student Record requests served by /coach/{ContactId}/teamseasons/{teamSeasonId}/enrollments needs to include a field IsComplete (bool) set by salesforce for the App.

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/salesforce-data-api#154]
Salesforce Ticket
https://github.com/AmericaSCORESBayArea/salesforce-environment/issues/15

Coach App Ticket
https://github.com/AmericaSCORESBayArea/AmericaScores-CoachApp/issues/315

**Comment by CritiqalPete** [comment]
this needs setup in Salesforce first

**Comment by AleksandrMolchagin** [comment]
Addressed in #199!
