### ISSUE TITLE
Endpoint for instantly enrolling a student with TeamSeasonID, ContactID

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/salesforce-data-api#191]
the goal of quickly enrolling a student in a TeamSeason requires a simplified endpoint.
### Supports:
https://github.com/AmericaSCORESBayArea/Student-Registration-React-Web/issues/74

### REQUIREMENTS
- /Contact has a GET-ENROLLMENTS method
- An array of Enrollments for that Contact ID is returned, by ID, TeamSeasonID, TeamSeasonName, StartDate, EndDate, SeasonName, TeamID, TeamName, SchoolSite (Account) ID, SchoolSite Name (Account) 
- The results can be limited by SchoolSite Name, SeasonName, TeamSeasonName, StartDate, EndDate (potentially ID's as alternative to values for Season, Account, TeamSeason)
- A Null response indicates no enrollment records found for that StudentID (and args)

**Comment by CritiqalPete** [comment]
added details with Student Registration in mind for @lautirozen

**Comment by AleksandrMolchagin** [comment]
> * TeamSeasonName, StartDate, EndDate, SeasonName

Is **TeamSeasonName** the same thing as **SeasonName**?

**Comment by AleksandrMolchagin** [comment]
@CritiqalPete, I implemented the get:contact/enrollments endpoint based on the requirements in a new file, contact.xml. You can find it on this branch: [feature/191-get-enrollments-endpoint](https://github.com/AmericaSCORESBayArea/salesforce-data-api/tree/feature/191-get-enrollments-endpoint).

There is a custom listener, test/contact/enrollments, created for testing purposes.

**Comment by AleksandrMolchagin** [comment]
Addressed in #193!
