### ISSUE TITLE
externalStudentId and externalStudentIdSource fields not connected in the /contacts GET API

### ISSUE THREAD

**Issue by matthewjerome** [AmericaSCORESBayArea/salesforce-data-api#75]
**Dependency**
Sync Robot

**Is your feature request related to a problem? Please describe.**
The updated implementation of the `/contacts` GET API still requires `firstName` and `lastName` in the request body and the response is not affected by the values entered in `externalStudentId` and `externalStudentIdSource`

**Describe the solution you'd like**
run in the mode [1] `firstName` and `lastName` or [2] `externalStudentId` and `externalStudentIdSource`

**Comment by CritiqalPete** [comment]
@archana-llamas @Ignacioals @matthewjerome is this Fixed?
