### ISSUE TITLE
Endpoint for Student Registration returns Student Contact

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/salesforce-data-api#80]
Supports returning a list of Contacts, creating a new contact, updating a contact

**Dependency**
Student-Web-Registration

Functional Requirements:
1. (Returning Students only) A Student Contact record (ContactID) (or list of records) can be retrieved based on the Primary Phone # on that record (after authentication)
2. (New Students only) A new Student Contact record is created once a user (new parent) has successfully completed authentication, starting with the Primary and Mobile Phone fields being populated with that number
3. The Student Record is updated with the values entered in the form by that user, to complete the registration

Families need to:
1. Authenticate using their mobile phone (Auth API returns ContactID) (AUTH API+FIREBASE)
2. Register a Student for the first time (POST Contact)
2. Change info on an existing record (PATCH)
3. Add a new student with the same family info (POST)
4. Retrieve all student contacts with the same mobile phone (GET)
5. Have the same phone number they use to authenticate appear on all records they access and create

ERROR CONDITIONS:
- A duplication error needs to be handled (if name and DOB match) by returning a detailed error message the user can share with Support

Client Apps:
https://github.com/AmericaSCORESBayArea/AmericaScores-CoachApp/issues/7
https://github.com/AmericaSCORESBayArea/student-registration/issues/25

**Comment by CritiqalPete** [comment]
@archana-llamas can you help us with this?

**Comment by matthewjerome** [comment]
here is a general workflow - the yellow highlighted box indicates what may be the minimal work to unlock this workflow

**Page Load:**
![Page Load Workflow](https://user-images.githubusercontent.com/24796700/146492698-00cee1c9-0f0c-4cae-a3b6-09c615c7fd87.png)

**New Registration** 
![New Registration Workflow](https://user-images.githubusercontent.com/24796700/146492720-8b3e6204-693f-452b-b026-4b1de5c90807.png)

**Update Registration**
![Update Registration Workflow](https://user-images.githubusercontent.com/24796700/146492761-a7de7342-3a0b-4a1a-add7-b2c672d07440.png)
