### ISSUE TITLE
Sessions endpoint returns details of Team, Team Season, and Region

### ISSUE THREAD

**Issue by lautirozen** [AmericaSCORESBayArea/salesforce-data-api#81]
**Dependency**
What app or project needs this?
AmericaScores-CoachApp
**Is your feature request related to a problem? 
I need to show Team's name, Season name  and Session time in the sessions screen. Also i need to filter the Team's by Region in  the Teams screen.

**Describe the solution you'd like**
I need the API to add to the return  payload in the /all endpoint the requested fields (Team name, Season name and Session time) so we don´t use another unrelated endpoint.  Also, I need the API to add the requested field (Team Region) to the return payload in the /coach/{coachId}/teamseasons endpoint.

**Comment by CritiqalPete** [comment]
@lautirozen let's try to use more descriptive titles in the tickets.
