### ISSUE TITLE
(bug) API Support Needed

### ISSUE THREAD

**Issue by matthewjerome** [AmericaSCORESBayArea/salesforce-data-api#99]
Submitting a new request to SANDBOX timesout : 

```
HTTP POST on resource ‘http://mule-worker-internal-salesforce-data-api.us-e2.cloudhub.io:8091/api-internal/contacts’ failed: Timeout exceeded.“”
```

Equivalent request in PROD (eg, expected behavior) : 
```
data: { ContactId: ‘0031T00004IVgk1QAD’ }
```

**Comment by matthewjerome** [comment]
with that said, the contact record IS actually created - just the API response does not send back the `ContactId`

**Comment by arch-jn** [comment]
@matthewjerome Hi, I had a look at this one. If you are getting a null ContactId back, it could be because there are duplicates in Salesforce and therefore a new Contact wasn't created. I will change the code so it gives an error message back if that's the case
